### ISSUE TITLE
value Error coming when model learning executed

### ISSUE THREAD

**Issue by ghost** [sryu1/jsbgym-examples#1]
model.learn(total_timesteps=10000000, callback=callback)
by this command , I am getting the error given below
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.

​
<img width="779" alt="1" src="https://user-images.githubusercontent.com/125783843/219929434-e9a7a93e-21fb-4c1f-8918-7257b6faee0f.png">
<img width="832" alt="2" src="https://user-images.githubusercontent.com/125783843/219929441-21b1e7aa-05a2-4037-8b0a-46a1eeafed82.png">

**Comment by sryu1** [comment]
Hi, did you use stable baselines for gymnasium? I accidentally forgot to say that you need it for that... I'll put it in readme right now.

**Comment by sryu1** [comment]
I'd recommend you use a venv so you don't have to get rid of the original stable baselines
```console
pip install git+https://github.com/sryu1/jsbgym git+https://github.com/DLR-RM/stable-baselines3@feat/gymnasium-support git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib@feat/gymnasium-support
```

**Comment by sryu1** [comment]
Yeah, could you just try using the snippet above and the update the code snippet? Tell me how it goes.

**Comment by ghost** [comment]
The error is solved. The Training started.. Thank you so much. You are Great

**Comment by sryu1** [comment]
👍
